# input data
root_dir: ./data/interim/recordings
samples_list: ./data/interim/recordings.csv
ecg_type: stress
ecg_leads: MDC_ECG_LEAD_II
    # - MDC_ECG_LEAD_I
    # - MDC_ECG_LEAD_II
    # - MDC_ECG_LEAD_III
    # - MDC_ECG_LEAD_AVR
    # - MDC_ECG_LEAD_AVL
    # - MDC_ECG_LEAD_AVF
    # - MDC_ECG_LEAD_V1
    # - MDC_ECG_LEAD_V2
    # - MDC_ECG_LEAD_V3
    # - MDC_ECG_LEAD_V4
    # - MDC_ECG_LEAD_V5
    # - MDC_ECG_LEAD_V6
features: plain_signal

# model definition
model: mlp
hidden_size: 1000

# hyperparams
lr: 1e-4
batch_size: 32
early_stopping_max_epochs: 10
early_stopping_patience: 3

num_cv_folds: 5
