# input data
data:
  root_dir: ./data/interim/recordings
  samples_list: ./data/interim/recordings.csv
  ecg_type: stress
ecg_leads: MDC_ECG_LEAD_II
features: intervals

# model definition
model: mlp
hidden_size: 300

# hyperparams
lr: 1e-4
momentum: 0.9
batch_size: 32
early_stopping_max_epochs: 10
early_stopping_patience: 3

num_cv_folds: 5
