# input data
root_dir: ./data/interim/recordings
samples_list: ./data/interim/recordings.csv
ecg_type: stress
ecg_leads: all
features: plain_signal
flatten_leads: no

# model definition
model: cnn2d
grid_search:
  module__dense_hidden_size: [64, 128, 256, 512, 1024, 2048]
  lr: [0.01, 0.001, 0.0005, 0.0001, 0.00005, 0.00001]
  batch_size: [32, 64, 128]

early_stopping_max_epochs: 30
early_stopping_patience: 3

num_cv_folds: 5
